apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: makefile
spec:
  platforms:
  - sha256: 15ef06a9a13e91f75948faabb4ffb724617fa0ed792024a51a7b427da412c2f0
    uri: https://github.com/JackySo-24x7classroom/public-resources/archives/kubectl-plugin-1.0.0.zip
    bin: makefile.sh
    files:
    - from: "/*/makefile/*"
      to: "."
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
  version: "v1.0.0"
  homepage: https://github.com/JackySo-24x7classroom/public-resources
  shortDescription: Select Makefiles with kubectl work and display its run options and variables
