apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: makefile
spec:
  platforms:
  - sha256: 08693adff2d25edc220ec8bf588e1586bec4dadddeced782807fb170a606112e
    uri: https://github.com/JackySo-24x7classroom/public-resources/archive/kubectl-plugin-1.0.1.zip
    bin: makefile.sh
    files:
    - from: "/*/makefile/*"
      to: "."
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
  version: "v1.0.1"
  homepage: https://github.com/JackySo-24x7classroom/public-resources
  shortDescription: Select Makefiles with kubectl work and display its run options and variables
